CREATE TABLE IF NOT EXISTS item (
    id INTEGER PRIMARY KEY,
    title VARCHAR(255) NOT NULL DEFAULT '',
    description VARCHAR(2550) NOT NULL DEFAULT '',
    location VARCHAR(255) NOT NULL DEFAULT'',
    cost BIGINT NULL NOT NULL DEFAULT 0,
    isMonthly TINYINT NOT NULL DEFAULT 0,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT NULL
);
