name: Push Request
run-name: Push commits by @${{ github.actor }}
on: push
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - run: go env -w GO111MODULE=auto
      - run: go get ./...

  Build:
    runs-on: ubuntu-latest
    steps:
      - run: go build -v cmd/main.go
      - run: go test -v ../... --cover

  Vulnerability-Checker:
    runs-on: ubuntu-latest
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.22
           go-package: ./...
