name: Push Request
run-name: Push commits by @${{ github.actor }}
on: push
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - run: go env -w GO111MODULE=auto
      - run: go get ./...

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test

  Vulnerability-Checker:
    runs-on: ubuntu-latest
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.22
           go-package: ./...
