name: Push Request
run-name: Push commits by @${{ github.actor }}
on: push
jobs:
  Vulnerability-Checker:
    runs-on: ubuntu-latest
    steps:
      - run: go build cmd/main.go
      - run: go mod download
      - run: govulncheck ./...
      - run: echo "This job's status is ${{ job.status }}
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: go test ./...
      - run : echo "Test have ${{ job.status }}"
