name: Push Request
run-name: Push commits by @${{ github.actor }}
on: push
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - run: go env -w GO111MODULE=auto
      - run: go get ./...
  Vulnerability-Checker:
    runs-on: ubuntu-latest
    steps:
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - run: govulncheck ./...
      - run: echo "Vulnerability check is ${{ job.status }}
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: go test ./...
      - run : echo "Tests have ${{ job.status }}"
